### ISSUE TITLE
ImportError: deepspeed>=0.9.3 is required for a normal functioning of this module, but found deepspeed==0.9.2+git25d5540.abi0.dtk2304.torch1.13.1.

### ISSUE THREAD

**Issue by Modas-Li** [yuguo-Jack/ChatGLM-6B-in-DeepSpeed-Chat#2]
Traceback (most recent call last):
  File "/data/ChatGLM-6B-in-DeepSpeed-Chat-main/training/step1_supervised_finetuning/main.py", line 354, in <module>
    main()
  File "/data/ChatGLM-6B-in-DeepSpeed-Chat-main/training/step1_supervised_finetuning/main.py", line 210, in main
    model = create_hf_model(AutoModelForCausalLM,
  File "/data/ChatGLM-6B-in-DeepSpeed-Chat-main/training/utils/model/model_utils.py", line 32, in create_hf_model
    dschf = HfDeepSpeedConfig(ds_config)
  File "/usr/local/lib/python3.9/site-packages/transformers/integrations/deepspeed.py", line 65, in __init__
    dep_version_check("deepspeed")
  File "/usr/local/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 63, in dep_version_check
    require_version(deps[pkg], hint)
  File "/usr/local/lib/python3.9/site-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/usr/local/lib/python3.9/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: deepspeed>=0.9.3 is required for a normal functioning of this module, but found deepspeed==0.9.2+git25d5540.abi0.dtk2304.torch1.13.1.

**Comment by yuguo-Jack** [comment]
版本检查注释了
